Feat: Google Auth Draft
Hack4Impact-UMD/swaliga-foundation pull request #9
Opened 2024-03-04 16:42 UTC by home0712

I've just uploaded the updated code, and I added the following:
- added the function to sign in with a google account
- added the function to verify the google access token
- added the function to sign out the current user

However, I need some more time to address the following issues:

1. Due to google's policy, an existing user (who created an account using email/pwd and used a [gmail.com](http://gmail.com/) domain) is automatically overwritten by the google account when the user attempts to sign in with google. For example, an existing account using the email address [ex@gmail.com](mailto:ex@gmail.com) is overwritten by the google account associated with the same email [ex@gmail.com](mailto:ex@gmail.com). However, the uid is maintained.

- To solve this problem, I've been searching for a lot of approaches and I have come up with some ideas, but I need more time to find a better solution and to implement it.
- One potential solution is _**linking accounts**_, and it also needs some time to complete. If you think this is the best solution, let me know.

2. Redirection to main page

- when the access token is expired, we need to redirect users to the main page or login page to request that they login again. I also need more time to implement this feature.

2024-03-05 00:01 UTC, nkanchinadam reviewed
comments left on files

2024-03-05 00:02 UTC, nkanchinadam requested changes
comments left on files

2024-03-05 00:38 UTC, home0712 commented
@nkanchinadam @ukataria I've just reviewed the comments and changed the code.

2024-03-06 02:38 UTC, nkanchinadam approved these changes

2024-03-06 02:38 UTC, merged